### ISSUE TITLE
Add root Build CRD

### ISSUE THREAD

**Issue by mcbenjemaa** [forge-build/forge#12]
CRD is added,

add spec and status fields:

First iteration:

```yaml
apiVersion: image.forge.build/v1alpha1
kind: Build
metadata:
  name: build-sample
spec:
    infrastructureRef:
      kind: AWSBuild
      name: ubuntu-2204
      apiVersion: infrastructure.forge.build/v1alpha1
status:
  ready: true
  infrastructureReady: true
  provisionersReady: true
  connected: true
  phase: Building
  provisioners:
  - name: shell
     status: SUCCESS|FAILED
  - name: ansible
     status: SUCCESS|FAILED   

```

Spec infraRef: https://github.com/kubernetes-sigs/cluster-api/blob/main/api/v1beta1/cluster_types.go#L66

Status: https://github.com/kubernetes-sigs/cluster-api/blob/main/api/v1beta1/cluster_types.go#L390
